name: experiments
on:
  push:
    tags:
      - "run-example*"
env:
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  PYTHONPATH: ${{ github.workspace }}
  AWS_ACCESS_KEY_ID: ${{ secrets.MINIO_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.MINIO_SECRET_ACCESS_KEY }}
  MLFLOW_S3_ENDPOINT_URL: https://minio.kdl-dell.konstellation.io
  # TODO: Change bucket name
  MLFLOW_URL: https://<bucket-name>-mlflow.kdl-dell.konstellation.io
jobs:
  train-and-report:
    runs-on: ["self-hosted", "igz", "cpu"]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9.11"

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: dschep/install-pipenv-action@v1

      - uses: iterative/setup-dvc@v1

      - name: GIT setup
        run: |
          git config --global user.name "Continuous Development"
          git config --global user.email "oauth2@users.noreply.github.com"           
          dvc remote modify --local minio access_key_id ${{ env.AWS_ACCESS_KEY_ID }}
          dvc remote modify --local minio secret_access_key ${{ env.AWS_SECRET_ACCESS_KEY }}

      - name: Pipenv setup
        run: |
          pipenv sync --system

      - name: Run Experiment
        run: |
          dvc repro --pull

      - name: Share experiment
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw#*/}
          commit_message=$(git show -s --format=%B $branch)
          commit_message="${commit_message}-results"
          git add dvc.lock
          git commit -m "$commit_message"
          dvc push
          git push origin "HEAD:$branch"
